plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'top.blackcyan'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/public/' }
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.51.1.0'
    implementation 'com.formdev:flatlaf:3.5'
    implementation 'com.formdev:flatlaf-intellij-themes:3.5'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.vladsch.flexmark:flexmark-all:0.64.8'
}

shadowJar {
    archiveBaseName.set('PolyChat')
    archiveClassifier.set('all')
    manifest {
        attributes(
                'Main-Class': 'gui.window.MainWindow'
        )
    }
}

tasks.register('printVersion') {
    doLast {
        println project.version
    }
}

tasks.register('writeVersion') {
    doLast {
        def versionFile = layout.buildDirectory.file('version.txt').get().asFile
        versionFile.parentFile.mkdirs()
        versionFile.text = project.version
    }
}